name: 'cloudtype-github-action-deploy'
description: 'Cloudtype Github Actions - Deploy'
author: 'Cloudtype Inc'
inputs:
  CLOUDTYPE_TOKEN:
    description: 'Cloudtype token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
