on:
  workflow_dispatch:
jobs:
  hello-my-actions:
    runs-on: ubuntu-latest
    name: Cloudtype Deploy
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Extract branch name
        uses: vazco/github-actions-branch-name@v1
        id: branch
      - name: setup deploy key
        uses: cloudtype-github-actions/deploykey@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          repo: ${{ github.repository }}
      - name: deploy
        uses: ./
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          value: ${{ github.ref_name }}
          project: test
          stage: main
          yaml: |-
            name: myproject
            app: html
            options:
              git:
                branch: ${{ steps.branch.outputs.branch_name }}
                url: git@github.com:${{ github.repository }}.git
              docbase: /